### PR TITLE
Add rg353v config and update DEVICES.md

### PR DESCRIPTION
**Pull request by antonioalmeida**
First of all, amazing work! 

I got this working on the RG353V by following your instructions and #2. The only difference to the RG353P seems to be the joystick's GUID. 

I've added a `rm8-rg353v.json` config file and updated `DEVICES.md` to include the RG353V

### CODE REVIEW

**Comment by antonioalmeida** [comment]
Hey @konsumer no rush, but just checking if you saw this one

**Comment by konsumer** [comment]
> Hey @konsumer no rush, but just checking if you saw this one

I missed it for some reason! Merging. Thanks for the PR.

At some point, I could add some logic like this:

if no joystick in rm8.json, get ID for first and add it with basic mapping (so user can use it to go through config and set it up how they want without keyboard.)

**Comment by antonioalmeida** [comment]
hey @konsumer maybe launch a release with this in it? the repo is going around the m8 discord but the rg353v config file is currently not included

**Comment by konsumer** [comment]
@antonioalmeida I redid tagging, and published as `0.0.1`. It will take a while to get through CI, but we should have the assets, soon.

**Pull request merged**
